# JSON examples and exercise
****
+ get familiar with packages for dealing with JSON
+ study examples with JSON strings and files 
+ work on exercise to be completed and submitted 
****
+ reference: http://pandas.pydata.org/pandas-docs/stable/io.html#io-json-reader
+ data source: http://jsonstudio.com/resources/
****

In [2]:
import pandas as pd

## imports for Python, Pandas

In [2]:
import json
from pandas.io.json import json_normalize

## JSON example, with string

+ demonstrates creation of normalized dataframes (tables) from nested json string
+ source: http://pandas.pydata.org/pandas-docs/stable/io.html#normalization

In [5]:
# define json string
data = [{'state': 'Florida', 
         'shortname': 'FL',
         'info': {'governor': 'Rick Scott'},
         'counties': [{'name': 'Dade', 'population': 12345},
                      {'name': 'Broward', 'population': 40000},
                      {'name': 'Palm Beach', 'population': 60000}]},
        {'state': 'Ohio',
         'shortname': 'OH',
         'info': {'governor': 'John Kasich'},
         'counties': [{'name': 'Summit', 'population': 1234},
                      {'name': 'Cuyahoga', 'population': 1337}]}]

In [6]:
# use normalization to create tables from nested element
json_normalize(data, 'counties')

         name  population
0        Dade       12345
1     Broward       40000
2  Palm Beach       60000
3      Summit        1234
4    Cuyahoga        1337

In [7]:
# further populate tables created from nested element
json_normalize(data, 'counties', ['state', 'shortname', ['info', 'governor']])

         name  population    state shortname info.governor
0        Dade       12345  Florida        FL    Rick Scott
1     Broward       40000  Florida        FL    Rick Scott
2  Palm Beach       60000  Florida        FL    Rick Scott
3      Summit        1234     Ohio        OH   John Kasich
4    Cuyahoga        1337     Ohio        OH   John Kasich

****
## JSON example, with file

+ demonstrates reading in a json file as a string and as a table
+ uses small sample file containing data about projects funded by the World Bank 
+ data source: http://jsonstudio.com/resources/

In [4]:
# load json as string
json.load((open('data/world_bank_projects_less.json')))

In [43]:
# load as Pandas dataframe
sample_json_df = pd.read_json('data/world_bank_projects_less.json')
sample_json_df

,_id,approvalfy,board_approval_month,boardapprovaldate,borrower,closingdate,country_namecode,countrycode,countryname,countryshortname,...,sectorcode,source,status,supplementprojectflg,theme1,theme_namecode,themecode,totalamt,totalcommamt,url
0,{'$oid': '52b213b38594d8a2be17c780'},1999,November,2013-11-12T00:00:00Z,FEDERAL DEMOCRATIC REPUBLIC OF ETHIOPIA,2018-07-07T00:00:00Z,Federal Democratic Republic of Ethiopia!$!ET,ET,Federal Democratic Republic of Ethiopia,Ethiopia,...,"ET,BS,ES,EP",IBRD,Active,N,"{'Name': 'Education for all', 'Percent': 100}","[{'name': 'Education for all', 'code': '65'}]",65,130000000,130000000,http://www.worldbank.org/projects/P129828/ethi...
1,{'$oid': '52b213b38594d8a2be17c781'},2015,November,2013-11-04T00:00:00Z,GOVERNMENT OF TUNISIA,NaN,Republic of Tunisia!$!TN,TN,Republic of Tunisia,Tunisia,...,"BZ,BS",IBRD,Active,N,"{'Name': 'Other economic management', 'Percent...","[{'name': 'Other economic management', 'code':...","54,24",0,4700000,http://www.worldbank.org/projects/P144674?lang=en

****
## JSON exercise

Using data in file 'data/world_bank_projects.json' and the techniques demonstrated above,
1. Find the 10 countries with most projects
2. Find the top 10 major project themes (using column 'mjtheme_namecode')
3. In 2. above you will notice that some entries have only the code and the name is missing. Create a dataframe with the missing names filled in.

In [11]:
import json

In [12]:
import pandas as pd 
json_df = pd.read_json('data/world_bank_projects.json')

In [13]:
json_df.head(3)

,_id,approvalfy,board_approval_month,boardapprovaldate,borrower,closingdate,country_namecode,countrycode,countryname,countryshortname,...,sectorcode,source,status,supplementprojectflg,theme1,theme_namecode,themecode,totalamt,totalcommamt,url
0,{'$oid': '52b213b38594d8a2be17c780'},1999,November,2013-11-12T00:00:00Z,FEDERAL DEMOCRATIC REPUBLIC OF ETHIOPIA,2018-07-07T00:00:00Z,Federal Democratic Republic of Ethiopia!$!ET,ET,Federal Democratic Republic of Ethiopia,Ethiopia,...,"ET,BS,ES,EP",IBRD,Active,N,"{'Percent': 100, 'Name': 'Education for all'}","[{'code': '65', 'name': 'Education for all'}]",65,130000000,130000000,http://www.worldbank.org/projects/P129828/ethi...
1,{'$oid': '52b213b38594d8a2be17c781'},2015,November,2013-11-04T00:00:00Z,GOVERNMENT OF TUNISIA,NaN,Republic of Tunisia!$!TN,TN,Republic of Tunisia,Tunisia,...,"BZ,BS",IBRD,Active,N,"{'Percent': 30, 'Name': 'Other economic manage...","[{'code': '24', 'name': 'Other economic manage...","54,24",0,4700000,http://www.worldbank.org/projects/P144674?lang=en
2,{'$oid': '52b213b38594d8a2be17c782'},2014,November,2013-11-01T00:00:00Z,MINISTRY OF FINANCE AND ECONOMIC DEVEL,NaN,Tuvalu!$!TV,TV,Tuvalu,Tuvalu,...,TI,IBRD,Active,Y,"{'Percent': 46, 'Name': 'Regional integration'}","[{'code': '47', 'name': 'Regional integration'...","52,81,25,47",6060000,6060000,http://www.worldbank.org/projects/P145310?lang=en

In [14]:
json_df.describe()

,approvalfy,grantamt,ibrdcommamt,idacommamt,lendprojectcost,totalamt,totalcommamt
count,500.000000,5.000000e+02,5.000000e+02,5.000000e+02,5.000000e+02,5.000000e+02,5.000000e+02
mean,2013.108000,4.432400e+06,3.286010e+07,3.542136e+07,1.547241e+08,6.828146e+07,7.271386e+07
std,0.722066,2.023307e+07,1.089197e+08,7.681431e+07,4.764211e+08,1.242662e+08,1.234705e+08
min,1999.000000,0.000000e+00,0.000000e+00,0.000000e+00,3.000000e+04,0.000000e+00,3.000000e+04
25%,2013.000000,0.000000e+00,0.000000e+00,0.000000e+00,6.472500e+06,0.000000e+00,5.000000e+06
50%,2013.000000,0.000000e+00,0.000000e+00,0.000000e+00,3.500000e+07,2.000000e+07,2.500000e+07
75%,2013.000000,1.695000e+06,0.000000e+00,3.700000e+07,1.021250e+08,8.625000e+07,9.045000e+07
max,2015.000000,3.650000e+08,1.307800e+09,6.000000e+08,5.170000e+09,1.307800e+09,1.307800e+09

In [17]:
json_df[['countryname','project_name']]

,countryname,project_name
0,Federal Democratic Republic of Ethiopia,Ethiopia General Education Quality Improvement...
1,Republic of Tunisia,TN: DTF Social Protection Reforms Support
2,Tuvalu,Tuvalu Aviation Investment Project - Additiona...
3,Republic of Yemen,Gov't and Civil Society Organization Partnership
4,Kingdom of Lesotho,Second Private Sector Competitiveness and Econ...
5,Republic of Kenya,Additional Financing for Cash Transfers for Or...
6,Republic of India,National Highways Interconnectivity Improvemen...
7,People's Republic of China,China Renewable Energy Scale-Up Program Phase II
8,Republic of India,Rajasthan Road Sector Modernization Project
9,Kingdom of Morocco,MA Accountability and Transparency DPL
10,Republic of South Sudan,Southern Sudan Emergency Food Crisis Response ...
11,Republic of India,Uttarakhand Disaster Recovery Project
12,Republic of Ghana,GH eTransform Ghana
13,Democratic Republic of Timor-Leste,Timor Leste Road Climate Resilience Project - ...
14,Hashemite Kingdom of Jordan,NATIONAL UNIFIED REGISTRY AND OUTREACH WORKER ...
15,Samoa,Enhanced Road Access Project
16,Samoa,Samoa Agriculture & Fisheries Cyclone Response...
17,Republic of Madagascar,Emergency Support to Education For all Project
18,Kingdom of Cambodia,Additional Financing for the Second Health Sec...
19,Kingdom of Morocco,DTF:MA- Support New Governance Framework
20,Kyrgyz Republic,SOCIAL COHESION THROUGH COMMUNITY-BASED DEVELO...
21,Nepal,Nepal: Pro-poor Urban Regeneration Pilot
22,Hashemite Kingdom of Jordan,Jordan- Emergency Services and Social Resilience
23,Republic of Tajikistan,Tajikistan JSDF Nutrition Grant Scale Up
24,Republic of Azerbaijan,AGRICULTURAL COMPETITIVENESS IMPROVEMENT PROJECT
25,East Asia and Pacific,Capturing Coral Reef Ecosystem Services (CCRES)
26,Lao People's Democratic Republic,Lao PDR Ninth Poverty Reduction Support Operation
27,Pacific Islands,Pacific Aviation Safety Office Reform
28,Solomon Islands,Additional Financing 2 - Solomon Islands Rural...
29,Republic of Mozambique,Water Resources Development Flood Response Add...
...,...,...
470,Republic of Liberia,Road Asset Management Project - Additional Fin...
471,People's Republic of Bangladesh,Rural Electrification and Renewable Energy Dev...
472,Republic of Armenia,Reports to Conventions - UNCCD - Armenia
473,Republic of Albania,Land Degradation Enabling Activities - Albania
474,Islamic Republic of Pakistan,PK: Punjab Cities Governance Improvement
475,Republic of Indonesia,Indonesia Infrastructure Guarantee Fund Project
476,Socialist Republic of Vietnam,Distribution Efficiency Project
477,Republic of Uzbekistan,Additional Financing for the Second Rural Ente...
478,Islamic Republic of Pakistan,Punjab Land Records Management and Information...
479,Republic of Guatemala,Strengthening the resilience capacity of Maya ...
480,Republic of Zambia,Zambia - Extractive Industries Transparency In...
481,Republic of India,India: ICDS Systems Strengthening & Nutrition ...
482,Republic of India,Karnataka Watershed Development II
483,Republic of India,IN: Development Policy Loan (DPL) to Promote I...
484,Republic of the Philippines,Multi Donor Facility - PH Mindanao Reconstruct...
485,Mongolia,Capacity Builiding for Emerging Infectious Dis...
486,Middle East and North Africa,5M: Displaced People in Jordan / Lebanon
487,United Mexican States,Sustainable Production Systems and Biodiversity
488,Federative Republic of Brazil,RIO STATE DEVELOPMENT POLICY LOAN III
489,The Independent State of Papua New Guine,Papua New Guinea Settlement Upgrading Programme
490,Nepal,Nepal PFM-MDTF Strengthening Civil Society Org...
491,West Bank and Gaza,Water Supply and Sanitation Improvements for W...
492,Islamic Republic of Pakistan,Pakistan: Promoting Girls' Education in Baloch...
493,People's Republic of Bangladesh,Revision and Alignment of NAP with UNCCD 10-ye...
494,Nepal,Nepal: Pilot Project for Seismic School Safety...
495,Jamaica,Technological Scale Up for Youth-led Urban Orn...
496,Lao People's Democratic Republic,Lao Eight Poverty Reduction Support
497,Republic of Guinea,Second Emergency Agricultural Productivity Sup...
498,Republic of Indonesia,Sustainable Management of Agricultural Researc...
499,Republic of Kenya,KENYA: NATIONAL URBAN TRANSPORT IMPROVEMENT PR...

In [21]:
json_df[ 'mjtheme_namecode'][:11]

0     [{'code': '8', 'name': 'Human development'}, {...
1     [{'code': '1', 'name': 'Economic management'},...
2     [{'code': '5', 'name': 'Trade and integration'...
3     [{'code': '7', 'name': 'Social dev/gender/incl...
4     [{'code': '5', 'name': 'Trade and integration'...
5     [{'code': '6', 'name': 'Social protection and ...
6     [{'code': '2', 'name': 'Public sector governan...
7     [{'code': '11', 'name': 'Environment and natur...
8     [{'code': '10', 'name': 'Rural development'}, ...
9     [{'code': '2', 'name': 'Public sector governan...
10    [{'code': '10', 'name': 'Rural development'}, ...
Name: mjtheme_namecode, dtype: object

In [24]:
data = {}
data = json_df[ 'mjtheme_namecode']
print(type(data))

<class 'pandas.core.series.Series'>

In [38]:
'''Ques1'''
import pandas as pd 
json_df = pd.read_json('data/world_bank_projects.json')
J_df = json_df.groupby('countryname')['project_name'].count()
J_df.sort_values(ascending = False)[:10]

countryname
People's Republic of China         19
Republic of Indonesia              19
Socialist Republic of Vietnam      17
Republic of India                  16
Republic of Yemen                  13
Nepal                              12
People's Republic of Bangladesh    12
Kingdom of Morocco                 12
Africa                             11
Republic of Mozambique             11
Name: project_name, dtype: int64

In [39]:
'''Ques2'''
import json
from pandas.io.json import json_normalize
data = json.load((open('data/world_bank_projects.json')))
df = json_normalize(data,'mjtheme_namecode')
df_data = df.groupby('name')['name'].count()
sort_df = df_data.sort_values(ascending = False)[:10]

In [40]:
sort_df

name
Environment and natural resources management    223
Rural development                               202
Human development                               197
Public sector governance                        184
Social protection and risk management           158
Financial and private sector development        130
                                                122
Social dev/gender/inclusion                     119
Trade and integration                            72
Urban development                                47
Name: name, dtype: int64

In [41]:
df.name = df.name.replace('','missing')

In [42]:
df

     code                                          name
0       8                             Human development
1      11                                       missing
2       1                           Economic management
3       6         Social protection and risk management
4       5                         Trade and integration
5       2                      Public sector governance
6      11  Environment and natural resources management
7       6         Social protection and risk management
8       7                   Social dev/gender/inclusion
9       7                   Social dev/gender/inclusion
10      5                         Trade and integration
11      4      Financial and private sector development
12      6         Social protection and risk management
13      6                                       missing
14      2                      Public sector governance
15      4      Financial and private sector development
16     11  Environment and natural resources management
17      8                                       missing
18     10                             Rural development
19      7                                       missing
20      2                      Public sector governance
21      2                      Public sector governance
22      2                      Public sector governance
23     10                             Rural development
24      2                                       missing
25     10                             Rural development
26      6         Social protection and risk management
27      6         Social protection and risk management
28     11  Environment and natural resources management
29      4                                       missing
...   ...                                           ...
1469    8                             Human development
1470    9                             Urban development
1471    6         Social protection and risk management
1472    6         Social protection and risk management
1473    9                             Urban development
1474    2                      Public sector governance
1475    2                      Public sector governance
1476   10                             Rural development
1477   11                                       missing
1478    8                             Human development
1479    7                   Social dev/gender/inclusion
1480   11  Environment and natural resources management
1481    5                                       missing
1482    6         Social protection and risk management
1483    8                                       missing
1484    4      Financial and private sector development
1485    7                   Social dev/gender/inclusion
1486    8                             Human development
1487    5                         Trade and integration
1488    2                      Public sector governance
1489    8                             Human development
1490   10                             Rural development
1491    6                                       missing
1492   10                             Rural development
1493   10                             Rural development
1494   10                             Rural development
1495    9                             Urban development
1496    8                             Human development
1497    5                         Trade and integration
1498    4      Financial and private sector development

[1499 rows x 2 columns]